name: Deploy Infrastructure

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cleanup Failed Stack
        run: |
          STATUS=$(aws cloudformation describe-stacks \
          --stack-name infrastructure-stack \
          --query "Stacks[0].StackStatus" \
          --output text 2>/dev/null || echo "DOES_NOT_EXIST")

          echo "Current stack status: $STATUS"

          if [ "$STATUS" == "ROLLBACK_COMPLETE" ] || [ "$STATUS" == "CREATE_FAILED" ]; then
          echo "Deleting failed stack..."
          aws cloudformation delete-stack --stack-name infrastructure-stack
          aws cloudformation wait stack-delete-complete --stack-name infrastructure-stack
          echo "Stack deleted successfully"
          else
          echo "Stack is in $STATUS state, no cleanup needed"
          fi

      - name: Deploy Infrastructure Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template--initial-infra.yaml \
            --stack-name infrastructure-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Output Infrastructure Stack Info
        run: |
          aws cloudformation describe-stacks \
            --stack-name infrastructure-stack \
            --query "Stacks[0].Outputs" \
            > infrastructure-outputs.json
          cat infrastructure-outputs.json

      - name: Upload infrastructure outputs to S3
        env:
         BUCKET_NAME: "expensetrackerinfra-${{ secrets.AWS_ACCOUNT_ID }}"
         INFRA_FILE_NAME: "infrastructure-outputs.json"
        run: |
          # Check if bucket exists
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
             echo "Bucket $BUCKET_NAME already exists"
          else
             echo "Creating bucket $BUCKET_NAME..."
             aws s3api create-bucket \
             --bucket "$BUCKET_NAME" \
             --region ${{ env.AWS_REGION }} \
             --create-bucket-configuration LocationConstraint=${{ env.AWS_REGION }}
          fi

          echo "Uploading to Bucket: $BUCKET_NAME"
          aws s3 cp $INFRA_FILE_NAME s3://$BUCKET_NAME/infrastructure-outputs.json
          echo "Successfully uploaded $INFRA_FILE_NAME to s3://$BUCKET_NAME/"
